### ISSUE TITLE
jitter and delayed sounds

### ISSUE THREAD

**Issue by PrestonKnopp** [timeyyy/orchestra.nvim#1]
Hi, first I wanna say that I'm really liking this plugin. It's like [power mode](https://atom.io/packages/activate-power-mode), but with sound!

Anyway, to the issue.

While typing the sound effects can be jittery, distorted, and also continue to play way after the last keystroke. This, I _think_, is a buffering issue.

I'll make a pull request with a simple fix.

**Comment by timeyyy** [comment]
thanks for looking into this, it's like 1000x better :)

**Comment by PrestonKnopp** [comment]
glad I could be of help :D

**Comment by timeyyy** [comment]
If you do the change as per my comment in the p/r i can merge :)

**Comment by PrestonKnopp** [comment]
Oh! Sorry, about that. Will do that now.
