### ISSUE TITLE
triggering rapid playback kills the sound

### ISSUE THREAD

**Issue by timeyyy** [timeyyy/orchestra.nvim#3]
after a few seconds of holding down a key, playback will simply stop. Each time a sound is played we spin off a thread. Not sure if that is related.

**Comment by PrestonKnopp** [comment]
I'm not getting the playback stoppage, using mac os x el capitan.

Maybe it could be a thread or open file count limit?

**Comment by timeyyy** [comment]
Yer i was thinking the same, i might have a look at some sort of thread pool.
