### ISSUE TITLE
Do you have any instructions for VimPlug?

### ISSUE THREAD

**Issue by jtopgi** [timeyyy/orchestra.nvim#5]

**Comment by timeyyy** [comment]
Plug 'timeyyy/orchestra.nvim'
Plug 'timeyyy/bubbletrouble.symphony'

Then as usual -> 
call orchestra#prelude()
call orchestra#set_tune('clackclack')

**Comment by jtopgi** [comment]
Thanks for your help. Here's how I got it to work.

MacOS VimPlug installation:
Commands:
`brew install portaudio`
`pip install pyaudio`
`pip install neovim`

My .vimrc
```
call plug#begin()
Plug 'timeyyy/orchestra.nvim'
Plug 'timeyyy/clackclack.symphony'
call plug#end()

call orchestra#prelude()
call orchestra#set_tune('clackclack')
```
then run these vim commands:
`:so %`
`:PlugInstall`
`:UpdateRemotePlugins`
reopen nvim
